# Generated by Django 6.1.1 on 2026-09-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userprofile_type_of_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
