# Generated by Django 6.1.1 on 2026-09-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('barangay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('barangay', models.ForeignKey(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='core.barangay')),
            ],
        ),
    ]
