# Generated by Django 6.1.1 on 2026-09-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barangay',
            table='barangay',
        ),
        migrations.AlterModelTable(
            name='sitio',
            table='sitio',
        ),
    ]
