# Generated by Django 6.1.1 on 2026-09-29 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='householdrecord',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='householdrecord',
            name='sitio',
            field=models.ForeignKey(db_column='sitio_id', on_delete=django.db.models.deletion.CASCADE, related_name='household_records', to='core.sitio'),
        ),
        migrations.AddField(
            model_name='householdrecord',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentrecord',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentrecord',
            name='encoder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentrecord',
            name='household',
            field=models.ForeignKey(db_column='household_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household', to='records.householdrecord'),
        ),
        migrations.AddField(
            model_name='residentrecord',
            name='significant_other',
            field=models.ForeignKey(db_column='significant_other_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='records.residentrecord'),
        ),
        migrations.AddField(
            model_name='residentrecord',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentchildrelationship',
            name='child_resident_id',
            field=models.ForeignKey(db_column='child_resident_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child', to='records.residentrecord'),
        ),
        migrations.AddField(
            model_name='parentchildrelationship',
            name='parent_resident_id',
            field=models.ForeignKey(db_column='parent_resident_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='records.residentrecord'),
        ),
        migrations.AddField(
            model_name='householdrecord',
            name='head_of_household',
            field=models.ForeignKey(db_column='head_of_household_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_head', to='records.residentrecord'),
        ),
    ]
