# Generated by Django 6.1.1 on 2026-09-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings',
        ),
    ]
