# Generated by Django 6.1.1 on 2026-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_user',
            field=models.CharField(choices=[('admin', 'Admin'), ('encoder', 'Encoder')], max_length=20),
        ),
    ]
